Test pre-commit hook, spotlessApply failure

diff --git a/scripts/pre-commit b/scripts/pre-commit
--- a/scripts/pre-commit
+++ b/scripts/pre-commit
@@ -5,11 +5,13 @@
 # This is needed as all files with changes might not be staged.
 stagedFiles=$(git diff --staged --name-only)
 
-# Part 2 - Apply the formatting:
+# Part 2 - Apply the formatting (plus store failure status):
 # This is the part where files might be altered during the formatting.
 # You could also run other plugin in addition to the formatting.
 echo "Running spotlessApply. Formatting code..."
 ./gradlew spotlessApply
+
+status=$?
 
 # Part 3 - Re-add staged files:
 # All files that were identified in Part 1 are staged with git add.
@@ -19,7 +21,5 @@ for file in $stagedFiles; do
     git add $file
   fi
 done
-
-status=$?
 
 exit $status
